DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  FIRST_NAME VARCHAR(250) NOT NULL,
  LAST_NAME VARCHAR(250) NOT NULL,
  AGE INT DEFAULT NOT NULL,
  ADDRESS VARCHAR(250) NOT NULL
);

INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, AGE,ADDRESS) VALUES
  ('Bishnu', 'Mishra', 38,'Varthur'),
  ('Saruv', 'Reddy', 28,'Marthalli');
 